-- AlterTable
ALTER TABLE "Table" ADD COLUMN     "posX" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "posY" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "jobTitle" TEXT;
