ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CAFE';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'TOKO';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'LAUNDRY';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'COUNTER';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'COMPANY';

ALTER TABLE "Tenant" ALTER COLUMN "businessType" SET DEFAULT 'CAFE';
