import { DashboardFrame, DeviceBars, DeviceHeading, DevicePanel, DeviceRows, MetricGrid, ProgressRow, StatusFooter, SupervisorFrame } from "./shared";
import type { ShowcaseDeviceProps } from "./types";

type Row = { title: string; detail: string; value: string; tone?: "success" | "warning" | "danger" | "info" };

function Metrics({ density, values }: { density: ShowcaseDeviceProps["density"]; values: Array<{ label: string; value: string; tone?: "neutral" | "success" | "warning" | "danger" }> }) {
  return <MetricGrid density={density} metrics={values} />;
}

function TabletMetrics({ density, values, rows, title, subtitle }: ShowcaseDeviceProps & { values: Array<{ label: string; value: string; tone?: "neutral" | "success" | "warning" | "danger" }>; rows: Row[]; title: string; subtitle: string }) {
  return <SupervisorFrame title={title} subtitle={subtitle}><Metrics density={density} values={values} /><DevicePanel title="Perlu tindakan"><DeviceRows rows={rows} /></DevicePanel><StatusFooter text="Data supervisor tersinkron" /></SupervisorFrame>;
}

export function CafeLaptop({ density, label }: ShowcaseDeviceProps) {
  return <DashboardFrame title={label} active="Operasional"><DeviceHeading title="Dashboard Cafe" subtitle="Kopi Nusantara · Shift pagi" /><Metrics density={density} values={[{ label: "Pesanan aktif", value: "18" }, { label: "Menunggu masak", value: "7", tone: "warning" }, { label: "Siap saji", value: "5", tone: "success" }, { label: "Meja terisi", value: "12/20" }]} /><div className="bs-app-columns"><DevicePanel title="Kitchen display"><DeviceRows rows={[{ title: "B#12 · Latte", detail: "Meja 04 · 3 item", value: "3 mnt", tone: "warning" }, { title: "B#13 · Rice bowl", detail: "Takeaway · 2 item", value: "Baru", tone: "info" }, { title: "B#09 · Croissant", detail: "Meja 02 · 1 item", value: "Siap", tone: "success" }]} /></DevicePanel><DevicePanel title="Stok bahan"><DeviceRows rows={[{ title: "Susu full cream", detail: "Sisa 6 L · min. 12 L", value: "Restock", tone: "danger" }, { title: "Biji kopi arabika", detail: "Sisa 2 kg", value: "Aman", tone: "success" }]} /></DevicePanel></div><DevicePanel title="Penjualan per jam" className="is-wide"><DeviceBars values={[34, 55, 42, 78, 61, 88, 72]} labels={["10", "12", "14", "16", "18", "20", "21"]} /></DevicePanel></DashboardFrame>;
}
export function CafeTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Supervisor Cafe" subtitle="Shift pagi · 08:00" values={[{ label: "Order aktif", value: "18" }, { label: "Rata-rata", value: "16 mnt" }, { label: "Stok tipis", value: "2", tone: "warning" }, { label: "Meja", value: "12/20" }]} rows={[{ title: "Antrean dapur", detail: "7 pesanan belum dimasak", value: "Buka", tone: "warning" }, { title: "Meja 08", detail: "Pesanan siap antar", value: "Antar", tone: "success" }]} />; }

export function TokoLaptop({ density, label }: ShowcaseDeviceProps) { return <DashboardFrame title={label}><DeviceHeading title="Ringkasan Toko" subtitle="Toko Berkah · Hari ini" /><Metrics density={density} values={[{ label: "Omzet hari ini", value: "Rp12,8jt", tone: "success" }, { label: "Transaksi", value: "256" }, { label: "Item terjual", value: "1.024" }, { label: "Margin kotor", value: "28%" }]} /><div className="bs-app-columns"><DevicePanel title="Low stock"><DeviceRows rows={[{ title: "Beras premium 5kg", detail: "Sisa 4 · min. 10", value: "Restock", tone: "warning" }, { title: "Minyak goreng 2L", detail: "Sisa 7 · min. 15", value: "Restock", tone: "warning" }, { title: "Gula pasir 1kg", detail: "Sisa 2 · min. 8", value: "Urgent", tone: "danger" }]} /></DevicePanel><DevicePanel title="Barang masuk hari ini"><DeviceRows rows={[{ title: "PO #482", detail: "PT Sinar Jaya · 120 item", value: "Terima", tone: "info" }, { title: "PO #481", detail: "CV Makmur · 80 item", value: "QC", tone: "warning" }]} /></DevicePanel></div><div className="bs-app-columns"><DevicePanel title="Produk terlaris"><DeviceRows rows={[{ title: "Kopi bubuk 200g", detail: "Stok 24", value: "43 jual", tone: "success" }, { title: "Sabun mandi", detail: "Stok 30", value: "38 jual", tone: "success" }]} /></DevicePanel><DevicePanel title="Aktivitas stok"><DeviceBars values={[48, 56, 62, 50, 76, 82]} /></DevicePanel></div></DashboardFrame>; }
export function TokoTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Supervisor Toko" subtitle="Hari ini · 256 transaksi" values={[{ label: "Omzet", value: "Rp12,8jt" }, { label: "Stok tipis", value: "12", tone: "warning" }, { label: "PO datang", value: "3" }, { label: "Retur", value: "2", tone: "danger" }]} rows={[{ title: "Verifikasi penerimaan", detail: "PO #482 menunggu QC", value: "Buka", tone: "warning" }, { title: "Gula pasir", detail: "Stok di bawah minimum", value: "Pesan", tone: "danger" }]} />; }

export function SupermarketLaptop({ density, label }: ShowcaseDeviceProps) { return <DashboardFrame title={label} active="Persediaan"><DeviceHeading title="Warehouse Control" subtitle="Sentosa Market · Gudang pusat" action="Shift pagi" /><Metrics density={density} values={[{ label: "Active PO", value: "23" }, { label: "Goods received", value: "12" }, { label: "QC issues", value: "7", tone: "danger" }, { label: "Active SKU", value: "8.642" }]} /><div className="bs-app-columns"><DevicePanel title="Near-expiry warnings"><DeviceRows rows={[{ title: "Susu UHT 1L", detail: "Batch 2407 · 14 hari", value: "6 hari", tone: "danger" }, { title: "Yogurt cup 100g", detail: "Batch 2406 · 20 pcs", value: "9 hari", tone: "warning" }, { title: "Roti tawar", detail: "Batch 2407 · 48 pcs", value: "2 hari", tone: "danger" }]} /></DevicePanel><DevicePanel title="Warehouse exceptions"><DeviceRows rows={[{ title: "Overstock", detail: "Gudang B · Rak 12", value: "12", tone: "warning" }, { title: "Storage limit", detail: "Gudang A · Dingin", value: "8", tone: "danger" }, { title: "Wrong location", detail: "Cek putaway", value: "5", tone: "info" }]} /></DevicePanel></div><DevicePanel title="PO aktif"><DeviceRows rows={[{ title: "PO-250615-0123", detail: "PT Sukses Abadi · 120 SKU", value: "Rp120jt", tone: "success" }, { title: "PO-250615-034", detail: "CV Sumber Makmur · 81 SKU", value: "QC", tone: "warning" }]} /></DevicePanel></DashboardFrame>; }
export function SupermarketTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Gudang Supervisor" subtitle="Gudang A · shift pagi" values={[{ label: "PO aktif", value: "23" }, { label: "QC", value: "7", tone: "danger" }, { label: "Expired", value: "16", tone: "warning" }, { label: "Opname", value: "82%" }]} rows={[{ title: "Batch 2407", detail: "Roti tawar habis dalam 2 hari", value: "Tindak", tone: "danger" }, { title: "Rak B-12", detail: "Stock count belum selesai", value: "Cek", tone: "warning" }]} />; }

export function LaundryLaptop({ density, label }: ShowcaseDeviceProps) { return <DashboardFrame title={label} active="Operasional"><DeviceHeading title="Laundry Operations" subtitle="Laundry Kilat · 128 order hari ini" /><Metrics density={density} values={[{ label: "Order masuk", value: "128" }, { label: "Proses cuci", value: "64" }, { label: "Siap diambil", value: "42", tone: "success" }, { label: "Terlambat", value: "8", tone: "danger" }]} /><DevicePanel title="Pipeline proses laundry" className="is-wide"><div className="bs-pipeline-wide"><ProgressRow label="Diterima" value={100} detail="128" /><ProgressRow label="Dicuci" value={70} detail="64" /><ProgressRow label="Dikeringkan" value={48} detail="51" /><ProgressRow label="Disetrika" value={34} detail="38" /><ProgressRow label="Siap diambil" value={28} detail="42" tone="success" /></div></DevicePanel><div className="bs-app-columns"><DevicePanel title="Order perlu perhatian"><DeviceRows rows={[{ title: "#128 · Sinta", detail: "Lewat estimasi 25 menit", value: "Telat", tone: "danger" }, { title: "#131 · Dimas", detail: "Sisa tagihan Rp20rb", value: "Tagih", tone: "warning" }]} /></DevicePanel><DevicePanel title="Pembayaran belum lunas"><DeviceRows rows={[{ title: "#126 · Rani", detail: "Cuci kiloan", value: "Rp45rb", tone: "warning" }, { title: "#119 · Arief", detail: "Dry clean", value: "Rp80rb", tone: "warning" }]} /></DevicePanel></div></DashboardFrame>; }
export function LaundryTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Supervisor Laundry" subtitle="Hari ini · 128 order" values={[{ label: "Proses", value: "64" }, { label: "Siap", value: "42", tone: "success" }, { label: "Terlambat", value: "8", tone: "danger" }, { label: "Belum lunas", value: "5", tone: "warning" }]} rows={[{ title: "Cuci mesin 03", detail: "Selesai dalam 14 menit", value: "Pantau", tone: "info" }, { title: "#128 Sinta", detail: "Lewat estimasi", value: "Hubungi", tone: "danger" }]} />; }

export function CounterLaptop({ density, label }: ShowcaseDeviceProps) { return <DashboardFrame title={label} active="Operasional"><DeviceHeading title="Service Counter" subtitle="Konter Jaya · Meja servis" /><Metrics density={density} values={[{ label: "Tiket aktif", value: "36" }, { label: "Menunggu part", value: "14", tone: "warning" }, { label: "Siap ambil", value: "18", tone: "success" }, { label: "Penjualan", value: "Rp3,2jt" }]} /><div className="bs-app-columns"><DevicePanel title="Tiket servis aktif"><DeviceRows rows={[{ title: "KNT-032 · iPhone 13", detail: "Layar pecah · Andi", value: "Diagnosa", tone: "info" }, { title: "KNT-031 · Samsung A54", detail: "Ganti baterai · Rina", value: "Proses", tone: "warning" }, { title: "KNT-030 · Macbook Air", detail: "Cleaning · Deni", value: "Siap", tone: "success" }]} /></DevicePanel><DevicePanel title="Spare part dibutuhkan"><DeviceRows rows={[{ title: "LCD iPhone 13", detail: "Pesanan supplier", value: "14", tone: "warning" }, { title: "Baterai Samsung A54", detail: "Stok rak A-04", value: "4", tone: "success" }]} /></DevicePanel></div><div className="bs-app-columns"><DevicePanel title="Status perangkat"><DeviceBars values={[68, 43, 72, 56]} /></DevicePanel><DevicePanel title="Aktivitas terbaru"><DeviceRows rows={[{ title: "KNT-021", detail: "Teknisi mengubah status", value: "10:15", tone: "info" }, { title: "KNT-014", detail: "Pembayaran lunas", value: "09:42", tone: "success" }]} /></DevicePanel></div></DashboardFrame>; }
export function CounterTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Supervisor Counter" subtitle="Meja servis · hari ini" values={[{ label: "Tiket", value: "36" }, { label: "Part", value: "14", tone: "warning" }, { label: "Siap", value: "18", tone: "success" }, { label: "Urgent", value: "5", tone: "danger" }]} rows={[{ title: "KNT-032", detail: "Perlu diagnosa teknisi", value: "Buka", tone: "danger" }, { title: "LCD iPhone 13", detail: "14 perangkat menunggu", value: "Pesan", tone: "warning" }]} />; }

export function JasaLaptop({ density, label }: ShowcaseDeviceProps) { return <DashboardFrame title={label} active="Operasional"><DeviceHeading title="Booking & Staff" subtitle="Studio Utama · Jadwal hari ini" /><Metrics density={density} values={[{ label: "Booking hari ini", value: "24" }, { label: "Jadwal aktif", value: "18" }, { label: "Invoice belum lunas", value: "8", tone: "warning" }, { label: "Staf tersedia", value: "6", tone: "success" }]} /><div className="bs-app-columns"><DevicePanel title="Timeline janji temu"><DeviceRows rows={[{ title: "10:00 · Dwi Lestari", detail: "Hair treatment · Nia", value: "Selesai", tone: "success" }, { title: "13:00 · Raka H.", detail: "Konsultasi · Deni", value: "Datang", tone: "info" }, { title: "14:00 · Salsa", detail: "Potong + treatment", value: "DP", tone: "warning" }]} /></DevicePanel><DevicePanel title="Follow-up pelanggan"><DeviceRows rows={[{ title: "Rina Handayani", detail: "Follow up besok", value: "Hari ini", tone: "warning" }, { title: "PT Sejahtera", detail: "Menunggu invoice", value: "Besok", tone: "info" }]} /></DevicePanel></div><div className="bs-app-columns"><DevicePanel title="Invoice belum lunas"><DeviceRows rows={[{ title: "INV-205 · PT Maju Bersama", detail: "Jatuh tempo hari ini", value: "Rp275rb", tone: "danger" }]} /></DevicePanel><DevicePanel title="Utilisasi staf"><DeviceBars values={[64, 78, 52, 88, 42]} /></DevicePanel></div></DashboardFrame>; }
export function JasaTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Supervisor Jasa" subtitle="Agenda hari ini" values={[{ label: "Booking", value: "24" }, { label: "Staf", value: "6" }, { label: "No-show", value: "2", tone: "warning" }, { label: "Piutang", value: "Rp1,2jt", tone: "danger" }]} rows={[{ title: "Salsa · 14:00", detail: "Menunggu konfirmasi", value: "Hubungi", tone: "warning" }, { title: "PT Maju Bersama", detail: "Invoice jatuh tempo", value: "Tagih", tone: "danger" }]} />; }

export function PabrikLaptop({ density, label }: ShowcaseDeviceProps) { return <DashboardFrame title={label} active="Operasional"><DeviceHeading title="Production Control" subtitle="Roti Makmur · Line A & B" action="Shift 1" /><Metrics density={density} values={[{ label: "Work order aktif", value: "24" }, { label: "Target produksi", value: "12.450 pcs" }, { label: "Hasil aktual", value: "9.680 pcs", tone: "success" }, { label: "Reject", value: "245 pcs", tone: "danger" }]} /><div className="bs-app-columns"><DevicePanel title="Progress work order"><div className="bs-pipeline-wide"><ProgressRow label="WO-2405002 · Roti Sobek" value={85} detail="85%" /><ProgressRow label="WO-2405006 · Roti Tawar" value={62} detail="62%" /><ProgressRow label="WO-2405014 · Bun Coklat" value={40} detail="40%" /></div></DevicePanel><DevicePanel title="Downtime mesin"><DeviceRows rows={[{ title: "Oven CNC-01", detail: "Tidak aktif sejak 10:15", value: "2,1 jam", tone: "danger" }, { title: "Packing-02", detail: "Setup ulang", value: "0,6 jam", tone: "warning" }]} /></DevicePanel></div><div className="bs-app-columns"><DevicePanel title="Material kurang"><DeviceRows rows={[{ title: "Tepung terigu", detail: "Stok 300 kg · butuh 500 kg", value: "Kurang", tone: "danger" }, { title: "Gula pasir", detail: "Stok 200 kg", value: "Aman", tone: "success" }]} /></DevicePanel><DevicePanel title="QC issues terbaru"><DeviceRows rows={[{ title: "QC-2405014", detail: "Dimensi tidak sesuai", value: "12 pcs", tone: "warning" }, { title: "QC-2405012", detail: "Warna terlalu gelap", value: "8 pcs", tone: "danger" }]} /></DevicePanel></div></DashboardFrame>; }
export function PabrikTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Supervisor Produksi" subtitle="20 Mei 2026 · Shift 1" values={[{ label: "Target", value: "12.450" }, { label: "Aktual", value: "9.680", tone: "success" }, { label: "Reject", value: "245", tone: "danger" }, { label: "QC", value: "12", tone: "warning" }]} rows={[{ title: "Oven CNC-01", detail: "Berhenti sejak 10:15", value: "Tinggi", tone: "danger" }, { title: "Tepung terigu", detail: "Bahan baku menipis", value: "Pesan", tone: "warning" }]} />; }

export function CompanyLaptop({ density, label }: ShowcaseDeviceProps) { return <DashboardFrame title={label}><DeviceHeading title="Perusahaan Nusantara" subtitle="Ringkasan seluruh cabang" /><Metrics density={density} values={[{ label: "Approval menunggu", value: "18", tone: "warning" }, { label: "Kas masuk", value: "Rp1,25 M" }, { label: "Kas keluar", value: "Rp860 jt" }, { label: "Jatuh tempo", value: "23", tone: "danger" }]} /><div className="bs-app-columns"><DevicePanel title="Performa cabang YTD"><DeviceBars values={[70, 92, 63, 84, 56]} labels={["JKT", "SBY", "BDG", "MKS", "DPS"]} /></DevicePanel><DevicePanel title="Cabang bermasalah"><DeviceRows rows={[{ title: "Makassar", detail: "Margin -5% dari target", value: "Periksa", tone: "danger" }, { title: "Medan", detail: "Piutang tinggi", value: "Pantau", tone: "warning" }, { title: "Bandung", detail: "Penjualan turun 15%", value: "Tindak", tone: "warning" }]} /></DevicePanel></div><div className="bs-app-columns"><DevicePanel title="Inbox approval"><DeviceRows rows={[{ title: "PR-240501 · Pembelian", detail: "Cabang Jakarta", value: "Rp15jt", tone: "warning" }, { title: "TRV-240506 · Travel", detail: "Cabang Makassar", value: "Rp12jt", tone: "info" }]} /></DevicePanel><DevicePanel title="Perbandingan cabang"><DeviceRows rows={[{ title: "Jakarta", detail: "Pendapatan Rp2,1 M", value: "Baik", tone: "success" }, { title: "Surabaya", detail: "Pendapatan Rp1,6 M", value: "Baik", tone: "success" }]} /></DevicePanel></div></DashboardFrame>; }
export function CompanyTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Ringkasan Manajer" subtitle="Seluruh cabang · YTD" values={[{ label: "Pendapatan", value: "Rp4,15 M" }, { label: "Laba", value: "Rp900 jt", tone: "success" }, { label: "Margin", value: "21,4%" }, { label: "Approval", value: "18", tone: "warning" }]} rows={[{ title: "Cabang Makassar", detail: "Margin turun 5%", value: "Pantau", tone: "danger" }, { title: "PR-240501", detail: "Butuh persetujuan", value: "Setujui", tone: "warning" }]} />; }

export function TeamsLaptop({ density, label }: ShowcaseDeviceProps) { return <DashboardFrame title={label} active="Operasional"><DeviceHeading title="People Operations" subtitle="Cabang BSD · Senin, 12 Juli" /><Metrics density={density} values={[{ label: "Hadir", value: "18", tone: "success" }, { label: "Terlambat", value: "2", tone: "warning" }, { label: "Cuti menunggu", value: "4" }, { label: "Target tim", value: "72%" }]} /><div className="bs-app-columns"><DevicePanel title="Kehadiran hari ini"><DeviceRows rows={[{ title: "Sinta A.", detail: "Masuk 07:52 · foto tervalidasi", value: "Tepat", tone: "success" }, { title: "Bagus R.", detail: "Masuk 07:58 · 12m dari toko", value: "Tepat", tone: "success" }, { title: "Dewi K.", detail: "Masuk 08:14", value: "Telat", tone: "warning" }]} /></DevicePanel><DevicePanel title="Jadwal & approval"><DeviceRows rows={[{ title: "Tukar shift Jumat", detail: "Bagus R. ke Sinta A.", value: "Review", tone: "info" }, { title: "Cuti 16 Jul", detail: "Dewi K. · 1 hari", value: "Setuju", tone: "warning" }]} /></DevicePanel></div><DevicePanel title="Pencapaian target tim" className="is-wide"><DeviceBars values={[44, 58, 61, 72, 80, 72]} /></DevicePanel></DashboardFrame>; }
export function TeamsTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Supervisor Tim" subtitle="Cabang BSD · Shift pagi" values={[{ label: "Hadir", value: "18", tone: "success" }, { label: "Telat", value: "2", tone: "warning" }, { label: "Cuti", value: "4" }, { label: "Target", value: "72%" }]} rows={[{ title: "Dewi K.", detail: "Telat 14 menit", value: "Tinjau", tone: "warning" }, { title: "Tukar shift", detail: "Bagus R. · Jumat", value: "Setuju", tone: "info" }]} />; }

export function AccountingLaptop({ density, label }: ShowcaseDeviceProps) { return <DashboardFrame title={label} active="Laporan"><DeviceHeading title="Keuangan & Akuntansi" subtitle="Periode Juli 2026" /><Metrics density={density} values={[{ label: "Saldo kas", value: "Rp1,58 M", tone: "success" }, { label: "Total piutang", value: "Rp2,45 M" }, { label: "Total hutang", value: "Rp1,75 M", tone: "warning" }, { label: "Biaya hari ini", value: "Rp320 jt" }]} /><div className="bs-app-columns"><DevicePanel title="Cashflow 30 hari"><DeviceBars values={[74, 44, 68, 51, 86, 65, 92]} /></DevicePanel><DevicePanel title="Invoice overdue"><DeviceRows rows={[{ title: "INV-240501", detail: "PT Maju Bersama · 30 hari", value: "Rp85jt", tone: "danger" }, { title: "INV-240496", detail: "CV Sinar Jaya · 14 hari", value: "Rp24jt", tone: "warning" }]} /></DevicePanel></div><div className="bs-app-columns"><DevicePanel title="Rekonsiliasi bank"><DeviceRows rows={[{ title: "BCA · 1234567890", detail: "Mutasi cocok", value: "Cocok", tone: "success" }, { title: "Mandiri · 9876543210", detail: "Selisih Rp2.500", value: "Cek", tone: "danger" }]} /></DevicePanel><DevicePanel title="Aktivitas jurnal"><DeviceRows rows={[{ title: "Pembayaran supplier", detail: "JV-240501", value: "Rp45jt", tone: "info" }, { title: "Beban operasional", detail: "JV-240499", value: "Rp15jt", tone: "warning" }]} /></DevicePanel></div></DashboardFrame>; }
export function AccountingTablet(props: ShowcaseDeviceProps) { return <TabletMetrics {...props} title="Ringkasan Finance" subtitle="20 Mei 2026 · Periode aktif" values={[{ label: "Kas", value: "Rp1,58 M" }, { label: "Piutang", value: "Rp2,45 M" }, { label: "Hutang", value: "Rp1,75 M", tone: "warning" }, { label: "Laba", value: "Rp320 jt", tone: "success" }]} rows={[{ title: "Invoice overdue", detail: "23 invoice lewat tempo", value: "Tinggi", tone: "danger" }, { title: "Rekonsiliasi Mandiri", detail: "Selisih Rp2.500", value: "Cek", tone: "warning" }]} />; }
